#!/usr/bin/env bash
#**********************************************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Script generated by Vivado on Tue Dec 09 20:08:04 +10 2025
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved. 
#
# Filename     : system.sh
# Simulator    : Cadence Xcelium Parallel Simulator
# Description  : Simulation script generated by export_simulation Tcl command
# Purpose      : Run 'compile', 'elaborate', 'simulate' steps for compiling, elaborating and simulating the
#                design. The script will copy the library mapping file from the compiled library directory,
#                create design library directories and library mappings in the mapping file.
#
# Usage        : system.sh
#                system.sh [-lib_map_path] [-step] [-keep_index] [-noclean_files]*
#                system.sh [-reset_run]
#                system.sh [-reset_log]
#                system.sh [-help]
#
#               * The -noclean_files switch is deprecated and will not peform any function (by default, the
#                 simulator generated files will not be removed unless -reset_run switch is used)
#
# Prerequisite : Before running export_simulation, you must first compile the AMD simulation library
#                using the 'compile_simlib' Tcl command (for more information, run 'compile_simlib -help'
#                command in the Vivado Tcl shell). After compiling the library, specify the -lib_map_path
#                switch with the directory path where the library is created while generating the script
#                with export_simulation.
#
#                Alternatively, you can set the library path by setting the following project property:-
#
#                 set_property compxlib.<simulator>_compiled_library_dir <path> [current_project]
#
#                You can also point to the simulation library by either setting the 'lib_map_path' global
#                variable in this script or specify it with the '-lib_map_path' switch while executing this
#                script (type 'system.sh -help' for more information).
#
#                Note: For pure RTL based designs, the -lib_map_path switch can be specified later with the
#                generated script, but if design is targetted for system simulation containing SystemC/C++/C
#                sources, then the library path MUST be specified upfront when calling export_simulation.
#
#                For more information, refer 'Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#**********************************************************************************************************

# catch pipeline exit status
set -Eeuo pipefail

# set xmvhdl compile options
xmvhdl_opts="-64bit -messages -relax -logfile .tmp_log -update"

# set xmvlog compile options
xmvlog_opts="-64bit -messages -logfile .tmp_log -update"

# set xmelab elaboration options
xmelab_opts="-64bit -relax -access +rwc -namemap_mixgen -messages -logfile elaborate.log"

# set xmsim simulation options
xmsim_opts="-64bit -logfile simulate.log"

# set design libraries for elaboration
design_libs_elab="-libname xilinx_vip -libname xpm -libname axi_infrastructure_v1_1_0 -libname axi_vip_v1_1_15 -libname zynq_ultra_ps_e_vip_v1_0_15 -libname xil_defaultlib -libname lib_cdc_v1_0_2 -libname proc_sys_reset_v5_0_14 -libname xlconcat_v2_1_5 -libname xlconstant_v1_1_8 -libname smartconnect_v1_0 -libname axi_register_slice_v2_1_29 -libname util_reduced_logic_v2_0_5 -libname xilinx_vip -libname unisims_ver -libname unimacro_ver -libname secureip"

# set design libraries
design_libs=(simprims_ver xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_15 zynq_ultra_ps_e_vip_v1_0_15 xil_defaultlib lib_cdc_v1_0_2 proc_sys_reset_v5_0_14 xlconcat_v2_1_5 xlconstant_v1_1_8 smartconnect_v1_0 axi_register_slice_v2_1_29 util_reduced_logic_v2_0_5)

# simulation root library directory
sim_lib_dir="xcelium_lib"

# script info
echo -e "system.sh - Script generated by export_simulation (Vivado v2023.2 (64-bit)-id)\n"

# main steps
run()
{
  check_args $*
  setup
  if [[ ($b_step == 1) ]]; then
    case $step in
      "compile" )
       init_lib
       compile
      ;;
      "elaborate" )
       elaborate
      ;;
      "simulate" )
       simulate
      ;;
      * )
        echo -e "ERROR: Invalid or missing step '$step' (type \"./system.sh -help\" for more information)\n"
        exit 1
      esac
  else
    init_lib
    compile
    elaborate
    simulate
  fi
}

# RUN_STEP: <compile>
compile()
{
  xmvlog -work xilinx_vip $xmvlog_opts -sv +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
  "/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
  "/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
  "/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
  "/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
  "/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
  "/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
  "/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
  "/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee compile.log; cat .tmp_log > xmvlog.log 2>/dev/null

  xmvlog -work xpm $xmvlog_opts -sv +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "/opt/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
  "/opt/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
  "/opt/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xpm -V93 $xmvhdl_opts \
  "/opt/Xilinx/Vivado/2023.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log > xmvhdl.log 2>/dev/null

  xmvlog -work axi_infrastructure_v1_1_0 $xmvlog_opts +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_vip_v1_1_15 $xmvlog_opts -sv +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/5753/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work zynq_ultra_ps_e_vip_v1_0_15 $xmvlog_opts -sv +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl/zynq_ultra_ps_e_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_sys_ps8_0/sim/system_sys_ps8_0_vip_wrapper.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work lib_cdc_v1_0_2 -V93 $xmvhdl_opts \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work proc_sys_reset_v5_0_14 -V93 $xmvhdl_opts \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/408c/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_sys_rstgen_0/sim/system_sys_rstgen_0.vhd" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_sys_250m_rstgen_0/sim/system_sys_250m_rstgen_0.vhd" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_sys_500m_rstgen_0/sim/system_sys_500m_rstgen_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xlconcat_v2_1_5 $xmvlog_opts +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/147b/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_spi0_csn_concat_0/sim/system_spi0_csn_concat_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xlconstant_v1_1_8 $xmvlog_opts +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/d390/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_VCC_1_0/sim/system_VCC_1_0.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_GND_1_0/sim/system_GND_1_0.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_spi1_csn_concat_0/sim/system_spi1_csn_concat_0.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/7689/_1/common/up_axi.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/7689/axi_sysid.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_sysid_0_0/sim/system_axi_sysid_0_0.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c6a0/sysid_rom.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_rom_sys_0_0/sim/system_rom_sys_0_0.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/sim/bd_24fc.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_0/sim/bd_24fc_one_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_1/sim/bd_24fc_psr_aclk_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv" \
  "../../../../sdr.gen/sources_1/bd/system/ipshared/bd53/hdl/sc_switchboard_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_2/sim/bd_24fc_arinsw_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_3/sim/bd_24fc_rinsw_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_4/sim/bd_24fc_awinsw_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_5/sim/bd_24fc_winsw_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_6/sim/bd_24fc_binsw_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_7/sim/bd_24fc_aroutsw_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_8/sim/bd_24fc_routsw_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_9/sim/bd_24fc_awoutsw_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_10/sim/bd_24fc_woutsw_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_11/sim/bd_24fc_boutsw_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/sc_node_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_12/sim/bd_24fc_arni_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_13/sim/bd_24fc_rni_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_14/sim/bd_24fc_awni_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_15/sim/bd_24fc_wni_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_16/sim/bd_24fc_bni_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sdr.gen/sources_1/bd/system/ipshared/c6b2/hdl/sc_mmu_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_17/sim/bd_24fc_s00mmu_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sdr.gen/sources_1/bd/system/ipshared/abb8/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_18/sim/bd_24fc_s00tr_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sdr.gen/sources_1/bd/system/ipshared/7827/hdl/sc_si_converter_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_19/sim/bd_24fc_s00sic_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sdr.gen/sources_1/bd/system/ipshared/79ce/hdl/sc_axi2sc_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_20/sim/bd_24fc_s00a2s_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_21/sim/bd_24fc_sarn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_22/sim/bd_24fc_srn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_23/sim/bd_24fc_sawn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_24/sim/bd_24fc_swn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_25/sim/bd_24fc_sbn_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sdr.gen/sources_1/bd/system/ipshared/ebf7/hdl/sc_sc2axi_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_26/sim/bd_24fc_m00s2a_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_27/sim/bd_24fc_m00arn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_28/sim/bd_24fc_m00rn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_29/sim/bd_24fc_m00awn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_30/sim/bd_24fc_m00wn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_31/sim/bd_24fc_m00bn_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work smartconnect_v1_0 $xmvlog_opts -sv +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../sdr.gen/sources_1/bd/system/ipshared/6eea/hdl/sc_exit_v1_0_vl_rfs.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_32/sim/bd_24fc_m00e_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_33/sim/bd_24fc_m01s2a_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_34/sim/bd_24fc_m01arn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_35/sim/bd_24fc_m01rn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_36/sim/bd_24fc_m01awn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_37/sim/bd_24fc_m01wn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_38/sim/bd_24fc_m01bn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_39/sim/bd_24fc_m01e_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_40/sim/bd_24fc_m02s2a_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_41/sim/bd_24fc_m02arn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_42/sim/bd_24fc_m02rn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_43/sim/bd_24fc_m02awn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_44/sim/bd_24fc_m02wn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_45/sim/bd_24fc_m02bn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_46/sim/bd_24fc_m02e_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_47/sim/bd_24fc_m03s2a_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_48/sim/bd_24fc_m03arn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_49/sim/bd_24fc_m03rn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_50/sim/bd_24fc_m03awn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_51/sim/bd_24fc_m03wn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_52/sim/bd_24fc_m03bn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_53/sim/bd_24fc_m03e_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work axi_register_slice_v2_1_29 $xmvlog_opts +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ff9f/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/sim/system_axi_cpu_interconnect_0.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_sys_concat_intc_0_0/sim/system_sys_concat_intc_0_0.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_sys_concat_intc_1_0/sim/system_sys_concat_intc_1_0.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/common/ad_addsub.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/xilinx/common/ad_data_clk.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/xilinx/common/ad_data_in.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/xilinx/common/ad_data_out.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/common/ad_datafmt.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/xilinx/common/ad_dcfilter.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/common/ad_dds.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/common/ad_dds_1.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/common/ad_dds_2.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/common/ad_dds_cordic_pipe.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/common/ad_dds_sine.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/common/ad_dds_sine_cordic.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/common/ad_iqcor.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/xilinx/common/ad_mul.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/common/ad_pnmon.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/common/ad_pps_receiver.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/common/ad_rst.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/common/ad_tdd_control.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/xilinx/axi_ad9361_cmos_if.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/xilinx/axi_ad9361_lvds_if.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/axi_ad9361_rx.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/axi_ad9361_rx_channel.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/axi_ad9361_rx_pnmon.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/axi_ad9361_tdd.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/axi_ad9361_tdd_if.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/axi_ad9361_tx.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/axi_ad9361_tx_channel.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/common/up_adc_channel.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/common/up_adc_common.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/common/up_clock_mon.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/common/up_dac_channel.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/common/up_dac_common.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/common/up_delay_cntrl.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/common/up_tdd_cntrl.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/common/up_xfer_cntrl.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/_1/common/up_xfer_status.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/6579/axi_ad9361.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_ad9361_0/sim/system_axi_ad9361_0.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ce16/_1/common/util_pulse_gen.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ce16/util_tdd_sync.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_util_ad9361_tdd_sync_0/sim/system_util_ad9361_tdd_sync_0.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_util_ad9361_divclk_sel_concat_0/sim/system_util_ad9361_divclk_sel_concat_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work util_reduced_logic_v2_0_5 $xmvlog_opts +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/7747/hdl/util_reduced_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_util_ad9361_divclk_sel_0/sim/system_util_ad9361_divclk_sel_0.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/8a4a/util_clkdiv.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_util_ad9361_divclk_0/sim/system_util_ad9361_divclk_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_util_ad9361_divclk_reset_0/sim/system_util_ad9361_divclk_reset_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ecbb/_1/common/ad_mem.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ecbb/util_wfifo.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_util_ad9361_adc_fifo_0/sim/system_util_ad9361_adc_fifo_0.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/d362/common/ad_perfect_shuffle.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/d362/_1/util_pack_common/pack_ctrl.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/d362/_1/util_pack_common/pack_interconnect.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/d362/_1/util_pack_common/pack_network.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/d362/_1/util_pack_common/pack_shell.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/d362/util_cpack2_impl.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/d362/util_cpack2.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_util_ad9361_adc_pack_0/sim/system_util_ad9361_adc_pack_0.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2c96/sync_gray.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2c96/sync_bits.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2c96/sync_data.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2c96/sync_event.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f158/util_axis_fifo_address_generator.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f158/util_axis_fifo.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_ad9361_adc_dma_0/sim/system_axi_ad9361_adc_dma_0_pkg.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/_1/common/ad_mem_asym.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/address_generator.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/axi_dmac_burst_memory.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/axi_dmac_regmap.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/axi_dmac_regmap_request.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/axi_dmac_reset_manager.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/axi_dmac_resize_dest.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/axi_dmac_resize_src.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/axi_dmac_response_manager.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/axi_dmac_transfer.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/axi_register_slice.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/data_mover.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/dest_axi_mm.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/dest_axi_stream.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/dest_fifo_inf.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/dmac_2d_transfer.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/dmac_sg.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/request_arb.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/request_generator.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/response_generator.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/response_handler.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/splitter.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/src_axi_mm.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/src_axi_stream.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/src_fifo_inf.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99/axi_dmac.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_ad9361_adc_dma_0/sim/system_axi_ad9361_adc_dma_0.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/5b42/util_rfifo.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_ad9361_dac_fifo_0/sim/system_axi_ad9361_dac_fifo_0.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/4e47/util_upack2_impl.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/4e47/util_upack2.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_util_ad9361_dac_upack_0/sim/system_util_ad9361_dac_upack_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_ad9361_dac_dma_0/sim/system_axi_ad9361_dac_dma_0_pkg.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_ad9361_dac_dma_0/sim/system_axi_ad9361_dac_dma_0.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/sim/bd_31bd.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_0/sim/bd_31bd_one_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_1/sim/bd_31bd_psr_aclk_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_2/sim/bd_31bd_arsw_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_3/sim/bd_31bd_rsw_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_4/sim/bd_31bd_awsw_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_5/sim/bd_31bd_wsw_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_6/sim/bd_31bd_bsw_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_7/sim/bd_31bd_s00mmu_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_8/sim/bd_31bd_s00tr_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_9/sim/bd_31bd_s00sic_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_10/sim/bd_31bd_s00a2s_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_11/sim/bd_31bd_sawn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_12/sim/bd_31bd_swn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_13/sim/bd_31bd_sbn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_14/sim/bd_31bd_s01mmu_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_15/sim/bd_31bd_s01tr_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_16/sim/bd_31bd_s01sic_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_17/sim/bd_31bd_s01a2s_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_18/sim/bd_31bd_sarn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_19/sim/bd_31bd_srn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_20/sim/bd_31bd_m00s2a_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_21/sim/bd_31bd_m00arn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_22/sim/bd_31bd_m00rn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_23/sim/bd_31bd_m00awn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_24/sim/bd_31bd_m00wn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_25/sim/bd_31bd_m00bn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_26/sim/bd_31bd_m00e_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/sim/system_axi_hp1_interconnect_0.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/sim/bd_c0fd.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_0/sim/bd_c0fd_one_0.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvhdl -work xil_defaultlib -V93 $xmvhdl_opts \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_1/sim/bd_c0fd_psr_aclk_0.vhd" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvhdl.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts -sv +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_2/sim/bd_c0fd_arsw_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_3/sim/bd_c0fd_rsw_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_4/sim/bd_c0fd_awsw_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_5/sim/bd_c0fd_wsw_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_6/sim/bd_c0fd_bsw_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_7/sim/bd_c0fd_s00mmu_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_8/sim/bd_c0fd_s00tr_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_9/sim/bd_c0fd_s00sic_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_10/sim/bd_c0fd_s00a2s_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_11/sim/bd_c0fd_sarn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_12/sim/bd_c0fd_srn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_13/sim/bd_c0fd_s01mmu_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_14/sim/bd_c0fd_s01tr_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_15/sim/bd_c0fd_s01sic_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_16/sim/bd_c0fd_s01a2s_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_17/sim/bd_c0fd_sarn_1.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_18/sim/bd_c0fd_srn_1.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_19/sim/bd_c0fd_m00s2a_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_20/sim/bd_c0fd_m00arn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_21/sim/bd_c0fd_m00rn_0.sv" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_22/sim/bd_c0fd_m00e_0.sv" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/ec67/hdl" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/2fcd/hdl" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/9e99" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/c2c6" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/f0b6/hdl/verilog" +incdir+"../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ipshared/35de/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/e2ba/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/a29c/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/ae90/hdl/verilog" +incdir+"../../../../sdr.gen/sources_1/bd/system/ipshared/0e59/hdl/verilog" +incdir+"/opt/Xilinx/Vivado/2023.2/data/xilinx_vip/include" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/sim/system_axi_hp2_interconnect_0.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_clk_wiz.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_0/sim/bd_d5b8_ila_lib_0.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/sim/bd_d5b8.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_system_ila_0_0/sim/system_system_ila_0_0.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_system_ila_1_0/bd_0/ip/ip_0/sim/bd_15e9_ila_lib_0.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_system_ila_1_0/bd_0/sim/bd_15e9.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_system_ila_1_0/sim/system_system_ila_1_0.v" \
  "../../../../fmcomms2_zcu102.gen/sources_1/bd/system/sim/system.v" \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null

  xmvlog -work xil_defaultlib $xmvlog_opts \
  glbl.v \
  2>&1 | tee -a compile.log; cat .tmp_log >> xmvlog.log 2>/dev/null
}

# RUN_STEP: <elaborate>
elaborate()
{
  xmelab $xmelab_opts $design_libs_elab xil_defaultlib.system xil_defaultlib.glbl
}

# RUN_STEP: <simulate>
simulate()
{
  xmsim $xmsim_opts xil_defaultlib.system -input simulate.do
}

# STEP: setup
setup()
{
  # delete previous files for a clean rerun
  if [[ ($b_reset_run == 1) ]]; then
    reset_run
    echo -e "INFO: Simulation run files deleted.\n"
    exit 0
  fi

 # delete previous log files
  if [[ ($b_reset_log == 1) ]]; then
    reset_log
    echo -e "INFO: Simulation run log files deleted.\n"
    exit 0
  fi

  # add any setup/initialization commands here:-

  # <user specific commands>

}

# simulator index file/library directory processing
init_lib()
{
  if [[ ($b_keep_index == 1) ]]; then
    # keep previous design library mappings
    true
  else
    # define design library mappings
    create_lib_mappings
  fi

  if [[ ($b_keep_index == 1) ]]; then
    # do not recreate design library directories
    true
  else
    # create design library directories
    create_lib_dir
  fi
}

# define design library mappings
create_lib_mappings()
{
  file="hdl.var"
  touch $file

  file="cds.lib"
  if [[ -e $file ]]; then
    if [[ ($lib_map_path == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($lib_map_path == "") ]]; then
    lib_map_path="/home/trinh/sdr/project/sdr.cache/compile_simlib/xcelium"
  fi

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="INCLUDE $lib_map_path/cds.lib"
    echo $incl_ref >> $file
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="DEFINE $lib $sim_lib_dir/$lib"
    echo $mapping >> $file
  done
}

# create design library directory
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi
  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# delete generated data from the previous run
reset_run()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log system_sc.so .tmp_log xcelium_lib waves.shm c.obj)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# delete generated log files from the previous run
reset_log()
{
  files_to_remove=(xmvlog.log xmvhdl.log xmsc.log compile.log elaborate.log simulate.log diag_report.log xsc_report.log .tmp_log)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done
}

# check switch argument value
check_arg_value()
{
  if [[ ($1 == "-step") && (($2 != "compile") && ($2 != "elaborate") && ($2 != "simulate")) ]];then
    echo -e "ERROR: Invalid or missing step '$2' (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($1 == "-lib_map_path") && ($2 == "") ]];then
    echo -e "ERROR: Simulation library directory path not specified (type \"./system.sh -help\" for more information)\n"
    exit 1
  fi
}

# check command line arguments
check_args()
{
  arg_count=$#
  if [[ ("$#" == 1) && (("$1" == "-help") || ("$1" == "-h")) ]]; then
    usage
  fi
  while [[ "$#" -gt 0 ]]; do
    case $1 in
      -step)          check_arg_value $1 $2;step=$2;         b_step=1;         shift;;
      -lib_map_path)  check_arg_value $1 $2;lib_map_path=$2; b_lib_map_path=1; shift;;
      -gen_bypass)    b_gen_bypass=1    ;;
      -reset_run)     b_reset_run=1     ;;
      -reset_log)     b_reset_log=1     ;;
      -keep_index)    b_keep_index=1    ;;
      -noclean_files) b_noclean_files=1 ;;
      -help|-h)       ;;
      *) echo -e "ERROR: Invalid option specified '$1' (type "./top.sh -help" for more information)\n"; exit 1 ;;
    esac
     shift
  done

  # -reset_run is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_run == 1) ]]; then
    echo -e "ERROR: -reset_run switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -reset_log is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_reset_log == 1) ]]; then
    echo -e "ERROR: -reset_log switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -keep_index is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_keep_index == 1) ]]; then
    echo -e "ERROR: -keep_index switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi

  # -noclean_files is not applicable with other switches
  if [[ ("$arg_count" -gt 1) && ($b_noclean_files == 1) ]]; then
    echo -e "ERROR: -noclean_files switch is not applicable with other switches (type \"./top.sh -help\" for more information)\n"
    exit 1
  fi
}

# script usage
usage()
{
  msg="Usage: system.sh [-help]\n\
Usage: system.sh [-step]\n\
Usage: system.sh [-lib_map_path]\n\
Usage: system.sh [-reset_run]\n\
Usage: system.sh [-reset_log]\n\
Usage: system.sh [-keep_index]\n\
Usage: system.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-step <name>] -- Execute specified step (simulate)\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Delete simulator generated data files from the previous run and recreate simulator setup\n\
file/library mappings for a clean run. This switch will not execute steps defined in the script.\n\n\
NOTE: To keep simulator index file settings from the previous run, use the -keep_index switch\n\
NOTE: To regenerate simulator index file but keep the simulator generated files, use the -noclean_files switch\n\n\
[-reset_log] -- Delete simulator generated log files from the previous run\n\n\
[-keep_index] -- Keep simulator index file settings from the previous run\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run\n"
  echo -e $msg
  exit 0
}

# initialize globals
step=""
lib_map_path=""
b_step=0
b_lib_map_path=0
b_gen_bypass=0
b_reset_run=0
b_reset_log=0
b_keep_index=0
b_noclean_files=0

# launch script
run $*
