# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/trinh/sdr/project/system_constr.xdc

# Block Designs: bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: bd/system/ip/system_sys_ps8_0/system_sys_ps8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_ps8_0 || ORIG_REF_NAME==system_sys_ps8_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_250m_rstgen_0/system_sys_250m_rstgen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_250m_rstgen_0 || ORIG_REF_NAME==system_sys_250m_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_500m_rstgen_0/system_sys_500m_rstgen_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_500m_rstgen_0 || ORIG_REF_NAME==system_sys_500m_rstgen_0} -quiet] -quiet

# IP: bd/system/ip/system_spi0_csn_concat_0/system_spi0_csn_concat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_spi0_csn_concat_0 || ORIG_REF_NAME==system_spi0_csn_concat_0} -quiet] -quiet

# IP: bd/system/ip/system_VCC_1_0/system_VCC_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_VCC_1_0 || ORIG_REF_NAME==system_VCC_1_0} -quiet] -quiet

# IP: bd/system/ip/system_GND_1_0/system_GND_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_GND_1_0 || ORIG_REF_NAME==system_GND_1_0} -quiet] -quiet

# IP: bd/system/ip/system_spi1_csn_concat_0/system_spi1_csn_concat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_spi1_csn_concat_0 || ORIG_REF_NAME==system_spi1_csn_concat_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_sysid_0_0/system_axi_sysid_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_sysid_0_0 || ORIG_REF_NAME==system_axi_sysid_0_0} -quiet] -quiet

# IP: bd/system/ip/system_rom_sys_0_0/system_rom_sys_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rom_sys_0_0 || ORIG_REF_NAME==system_rom_sys_0_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_cpu_interconnect_0/system_axi_cpu_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_cpu_interconnect_0 || ORIG_REF_NAME==system_axi_cpu_interconnect_0} -quiet] -quiet

# Block Designs: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/bd_24fc.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_0/bd_24fc_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_1/bd_24fc_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_2/bd_24fc_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_3/bd_24fc_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_4/bd_24fc_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_5/bd_24fc_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_6/bd_24fc_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_7/bd_24fc_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_8/bd_24fc_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_9/bd_24fc_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_10/bd_24fc_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_11/bd_24fc_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_12/bd_24fc_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_13/bd_24fc_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_14/bd_24fc_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_15/bd_24fc_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_16/bd_24fc_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_17/bd_24fc_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_18/bd_24fc_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_19/bd_24fc_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_20/bd_24fc_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_21/bd_24fc_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_22/bd_24fc_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_23/bd_24fc_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_24/bd_24fc_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_25/bd_24fc_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_26/bd_24fc_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_27/bd_24fc_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_28/bd_24fc_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_29/bd_24fc_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_30/bd_24fc_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_31/bd_24fc_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_32/bd_24fc_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_33/bd_24fc_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_34/bd_24fc_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_35/bd_24fc_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_36/bd_24fc_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_37/bd_24fc_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_38/bd_24fc_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_39/bd_24fc_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_40/bd_24fc_m02s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_41/bd_24fc_m02arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_42/bd_24fc_m02rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_43/bd_24fc_m02awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_44/bd_24fc_m02wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_45/bd_24fc_m02bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_46/bd_24fc_m02e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_47/bd_24fc_m03s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_48/bd_24fc_m03arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_49/bd_24fc_m03rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_50/bd_24fc_m03awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_51/bd_24fc_m03wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_52/bd_24fc_m03bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_53/bd_24fc_m03e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_sys_concat_intc_0_0/system_sys_concat_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_concat_intc_0_0 || ORIG_REF_NAME==system_sys_concat_intc_0_0} -quiet] -quiet

# IP: bd/system/ip/system_sys_concat_intc_1_0/system_sys_concat_intc_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_sys_concat_intc_1_0 || ORIG_REF_NAME==system_sys_concat_intc_1_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9361_0/system_axi_ad9361_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ad9361_tdd_sync_0/system_util_ad9361_tdd_sync_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ad9361_tdd_sync_0 || ORIG_REF_NAME==system_util_ad9361_tdd_sync_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ad9361_divclk_sel_concat_0/system_util_ad9361_divclk_sel_concat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ad9361_divclk_sel_concat_0 || ORIG_REF_NAME==system_util_ad9361_divclk_sel_concat_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ad9361_divclk_sel_0/system_util_ad9361_divclk_sel_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ad9361_divclk_sel_0 || ORIG_REF_NAME==system_util_ad9361_divclk_sel_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ad9361_divclk_0/system_util_ad9361_divclk_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ad9361_divclk_0 || ORIG_REF_NAME==system_util_ad9361_divclk_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ad9361_divclk_reset_0/system_util_ad9361_divclk_reset_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ad9361_divclk_reset_0 || ORIG_REF_NAME==system_util_ad9361_divclk_reset_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ad9361_adc_fifo_0/system_util_ad9361_adc_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ad9361_adc_fifo_0 || ORIG_REF_NAME==system_util_ad9361_adc_fifo_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ad9361_adc_pack_0/system_util_ad9361_adc_pack_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ad9361_adc_pack_0 || ORIG_REF_NAME==system_util_ad9361_adc_pack_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9361_adc_dma_0/system_axi_ad9361_adc_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ad9361_adc_dma_0 || ORIG_REF_NAME==system_axi_ad9361_adc_dma_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9361_dac_fifo_0/system_axi_ad9361_dac_fifo_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ad9361_dac_fifo_0 || ORIG_REF_NAME==system_axi_ad9361_dac_fifo_0} -quiet] -quiet

# IP: bd/system/ip/system_util_ad9361_dac_upack_0/system_util_ad9361_dac_upack_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_util_ad9361_dac_upack_0 || ORIG_REF_NAME==system_util_ad9361_dac_upack_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_ad9361_dac_dma_0/system_axi_ad9361_dac_dma_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_ad9361_dac_dma_0 || ORIG_REF_NAME==system_axi_ad9361_dac_dma_0} -quiet] -quiet

# IP: bd/system/ip/system_axi_hp1_interconnect_0/system_axi_hp1_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_hp1_interconnect_0 || ORIG_REF_NAME==system_axi_hp1_interconnect_0} -quiet] -quiet

# Block Designs: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/bd_31bd.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_0/bd_31bd_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_1/bd_31bd_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_2/bd_31bd_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_3/bd_31bd_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_4/bd_31bd_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_5/bd_31bd_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_6/bd_31bd_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_7/bd_31bd_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_8/bd_31bd_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_9/bd_31bd_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_10/bd_31bd_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_11/bd_31bd_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_12/bd_31bd_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_13/bd_31bd_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_14/bd_31bd_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_15/bd_31bd_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_16/bd_31bd_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_17/bd_31bd_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_18/bd_31bd_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_19/bd_31bd_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_20/bd_31bd_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_21/bd_31bd_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_22/bd_31bd_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_23/bd_31bd_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_24/bd_31bd_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_25/bd_31bd_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_26/bd_31bd_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_axi_hp2_interconnect_0/system_axi_hp2_interconnect_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axi_hp2_interconnect_0 || ORIG_REF_NAME==system_axi_hp2_interconnect_0} -quiet] -quiet

# Block Designs: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/bd_c0fd.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_0/bd_c0fd_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_1/bd_c0fd_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_2/bd_c0fd_arsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_3/bd_c0fd_rsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_4/bd_c0fd_awsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_5/bd_c0fd_wsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_6/bd_c0fd_bsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_7/bd_c0fd_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_8/bd_c0fd_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_9/bd_c0fd_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_10/bd_c0fd_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_11/bd_c0fd_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_12/bd_c0fd_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_13/bd_c0fd_s01mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_14/bd_c0fd_s01tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_15/bd_c0fd_s01sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_16/bd_c0fd_s01a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_17/bd_c0fd_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_18/bd_c0fd_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_19/bd_c0fd_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_20/bd_c0fd_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_21/bd_c0fd_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_22/bd_c0fd_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_0_0/system_system_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_system_ila_0_0 || ORIG_REF_NAME==system_system_ila_0_0} -quiet] -quiet

# Block Designs: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/bd_d5b8.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8 || ORIG_REF_NAME==bd_d5b8} -quiet] -quiet

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_0/bd_d5b8_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_d5b8_ila_lib_0 || ORIG_REF_NAME==bd_d5b8_ila_lib_0} -quiet] -quiet

# IP: bd/system/ip/system_system_ila_1_0/system_system_ila_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_system_ila_1_0 || ORIG_REF_NAME==system_system_ila_1_0} -quiet] -quiet

# Block Designs: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_system_ila_1_0/bd_0/bd_15e9.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_15e9 || ORIG_REF_NAME==bd_15e9} -quiet] -quiet

# IP: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_system_ila_1_0/bd_0/ip/ip_0/bd_15e9_ila_lib_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bd_15e9_ila_lib_0 || ORIG_REF_NAME==bd_15e9_ila_lib_0} -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_sys_ps8_0/system_sys_ps8_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_sys_ps8_0/system_sys_ps8_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_ps8_0 || ORIG_REF_NAME==system_sys_ps8_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_sys_rstgen_0/system_sys_rstgen_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_rstgen_0 || ORIG_REF_NAME==system_sys_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_sys_250m_rstgen_0/system_sys_250m_rstgen_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_250m_rstgen_0 || ORIG_REF_NAME==system_sys_250m_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_sys_250m_rstgen_0/system_sys_250m_rstgen_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_250m_rstgen_0 || ORIG_REF_NAME==system_sys_250m_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_sys_500m_rstgen_0/system_sys_500m_rstgen_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_500m_rstgen_0 || ORIG_REF_NAME==system_sys_500m_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_sys_500m_rstgen_0/system_sys_500m_rstgen_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_sys_500m_rstgen_0 || ORIG_REF_NAME==system_sys_500m_rstgen_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_1/bd_24fc_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_1/bd_24fc_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_2/bd_24fc_arinsw_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_3/bd_24fc_rinsw_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_4/bd_24fc_awinsw_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_5/bd_24fc_winsw_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_6/bd_24fc_binsw_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_7/bd_24fc_aroutsw_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_8/bd_24fc_routsw_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_9/bd_24fc_awoutsw_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_10/bd_24fc_woutsw_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_11/bd_24fc_boutsw_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_12/bd_24fc_arni_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_12/bd_24fc_arni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_13/bd_24fc_rni_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_13/bd_24fc_rni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_14/bd_24fc_awni_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_14/bd_24fc_awni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_15/bd_24fc_wni_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_15/bd_24fc_wni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_16/bd_24fc_bni_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_16/bd_24fc_bni_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_20/bd_24fc_s00a2s_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_21/bd_24fc_sarn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_21/bd_24fc_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_22/bd_24fc_srn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_22/bd_24fc_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_23/bd_24fc_sawn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_23/bd_24fc_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_24/bd_24fc_swn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_24/bd_24fc_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_25/bd_24fc_sbn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_25/bd_24fc_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_26/bd_24fc_m00s2a_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_27/bd_24fc_m00arn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_27/bd_24fc_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_28/bd_24fc_m00rn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_28/bd_24fc_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_29/bd_24fc_m00awn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_29/bd_24fc_m00awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_30/bd_24fc_m00wn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_30/bd_24fc_m00wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_31/bd_24fc_m00bn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_31/bd_24fc_m00bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_33/bd_24fc_m01s2a_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_34/bd_24fc_m01arn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_34/bd_24fc_m01arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_35/bd_24fc_m01rn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_35/bd_24fc_m01rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_36/bd_24fc_m01awn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_36/bd_24fc_m01awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_37/bd_24fc_m01wn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_37/bd_24fc_m01wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_38/bd_24fc_m01bn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_38/bd_24fc_m01bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_40/bd_24fc_m02s2a_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_41/bd_24fc_m02arn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_41/bd_24fc_m02arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_42/bd_24fc_m02rn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_42/bd_24fc_m02rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_43/bd_24fc_m02awn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_43/bd_24fc_m02awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_44/bd_24fc_m02wn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_44/bd_24fc_m02wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_45/bd_24fc_m02bn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_45/bd_24fc_m02bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_47/bd_24fc_m03s2a_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_48/bd_24fc_m03arn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_48/bd_24fc_m03arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_49/bd_24fc_m03rn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_49/bd_24fc_m03rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_50/bd_24fc_m03awn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_50/bd_24fc_m03awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_51/bd_24fc_m03wn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_51/bd_24fc_m03wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_52/bd_24fc_m03bn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/bd_0/ip/ip_52/bd_24fc_m03bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_cpu_interconnect_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_cpu_interconnect_0 || ORIG_REF_NAME==system_axi_cpu_interconnect_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_ad9361_0/system_axi_ad9361_0_pps_constr.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/xilinx/common/up_xfer_cntrl_constr.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/xilinx/common/ad_rst_constr.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/xilinx/common/up_xfer_status_constr.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/xilinx/common/up_clock_mon_constr.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_ad9361_0/axi_ad9361_constr.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_0 || ORIG_REF_NAME==system_axi_ad9361_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_util_ad9361_tdd_sync_0/util_tdd_sync_constr.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_util_ad9361_tdd_sync_0 || ORIG_REF_NAME==system_util_ad9361_tdd_sync_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_util_ad9361_divclk_0/system_util_ad9361_divclk_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_util_ad9361_divclk_0/util_clkdiv_constr.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_util_ad9361_divclk_0 || ORIG_REF_NAME==system_util_ad9361_divclk_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_util_ad9361_divclk_reset_0/system_util_ad9361_divclk_reset_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_util_ad9361_divclk_reset_0 || ORIG_REF_NAME==system_util_ad9361_divclk_reset_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_util_ad9361_divclk_reset_0/system_util_ad9361_divclk_reset_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_util_ad9361_divclk_reset_0 || ORIG_REF_NAME==system_util_ad9361_divclk_reset_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_util_ad9361_adc_fifo_0/util_wfifo_constr.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_util_ad9361_adc_fifo_0 || ORIG_REF_NAME==system_util_ad9361_adc_fifo_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_ad9361_adc_dma_0/system_axi_ad9361_adc_dma_0_constr.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_adc_dma_0 || ORIG_REF_NAME==system_axi_ad9361_adc_dma_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_ad9361_dac_fifo_0/util_rfifo_constr.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_dac_fifo_0 || ORIG_REF_NAME==system_axi_ad9361_dac_fifo_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_ad9361_dac_dma_0/system_axi_ad9361_dac_dma_0_constr.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_ad9361_dac_dma_0 || ORIG_REF_NAME==system_axi_ad9361_dac_dma_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_1/bd_31bd_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_1/bd_31bd_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_2/bd_31bd_arsw_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_3/bd_31bd_rsw_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_4/bd_31bd_awsw_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_5/bd_31bd_wsw_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_6/bd_31bd_bsw_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_10/bd_31bd_s00a2s_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_11/bd_31bd_sawn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_11/bd_31bd_sawn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_12/bd_31bd_swn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_12/bd_31bd_swn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_13/bd_31bd_sbn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_13/bd_31bd_sbn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_17/bd_31bd_s01a2s_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_18/bd_31bd_sarn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_18/bd_31bd_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_19/bd_31bd_srn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_19/bd_31bd_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_20/bd_31bd_m00s2a_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_21/bd_31bd_m00arn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_21/bd_31bd_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_22/bd_31bd_m00rn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_22/bd_31bd_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_23/bd_31bd_m00awn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_23/bd_31bd_m00awn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_24/bd_31bd_m00wn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_24/bd_31bd_m00wn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_25/bd_31bd_m00bn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/bd_0/ip/ip_25/bd_31bd_m00bn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp1_interconnect_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_hp1_interconnect_0 || ORIG_REF_NAME==system_axi_hp1_interconnect_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_1/bd_c0fd_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_1/bd_c0fd_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_2/bd_c0fd_arsw_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_3/bd_c0fd_rsw_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_4/bd_c0fd_awsw_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_5/bd_c0fd_wsw_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_6/bd_c0fd_bsw_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_10/bd_c0fd_s00a2s_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_11/bd_c0fd_sarn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_11/bd_c0fd_sarn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_12/bd_c0fd_srn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_12/bd_c0fd_srn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_16/bd_c0fd_s01a2s_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_17/bd_c0fd_sarn_1_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_17/bd_c0fd_sarn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_18/bd_c0fd_srn_1_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_18/bd_c0fd_srn_1_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_19/bd_c0fd_m00s2a_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_20/bd_c0fd_m00arn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_20/bd_c0fd_m00arn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_21/bd_c0fd_m00rn_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_21/bd_c0fd_m00rn_0_clocks.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/smartconnect.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_axi_hp2_interconnect_0 || ORIG_REF_NAME==system_axi_hp2_interconnect_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d5b8_ila_lib_0 || ORIG_REF_NAME==bd_d5b8_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_d5b8_ila_lib_0 || ORIG_REF_NAME==bd_d5b8_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/ip/ip_0/bd_d5b8_ila_lib_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_system_ila_0_0/bd_0/bd_d5b8_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_system_ila_0_0/system_system_ila_0_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_15e9_ila_lib_0 || ORIG_REF_NAME==bd_15e9_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_system_ila_1_0/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_15e9_ila_lib_0 || ORIG_REF_NAME==bd_15e9_ila_lib_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_system_ila_1_0/bd_0/ip/ip_0/bd_15e9_ila_lib_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_system_ila_1_0/bd_0/bd_15e9_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/ip/system_system_ila_1_0/system_system_ila_1_0_ooc.xdc

# XDC: /home/trinh/sdr/project/fmcomms2_zcu102.gen/sources_1/bd/system/system_ooc.xdc
